version: '3'
services:

  app:
    build: .
    container_name: app
    entrypoint: dockerize -template ./.docker/app/.env:.env -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
    environment:
      - DB_HOST=db
      - DB_DATABASE=laravel
      - DB_PASSWORD=toor4242
      - DB_USERNAME=root224
      - DB_PORT=3306
    volumes:
      - .:/var/www
    networks:
      - app-networks
    depends_on:
      - db
      - redis

  nginx:
    build: ./.docker/nginx/
    container_name: nginx
    restart: always
    tty: true
    ports:
      - 8000:80
    volumes:
      - .:/var/www
      - ./.docker/nginx/templates:/etc/nginx/templates
    environment:
      - APP_HOST=app
      - APP_PORT=9000
    networks:
      - app-networks
    depends_on:
      - app

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_USER=root
    networks:
      - app-networks
    volumes:
      - ./.docker/dbdata:/var/lib/mysql

  redis:
    image: redis:alpine
    expose:
      - 6379
    networks:
      - app-networks

networks:
  app-networks:
    driver: bridge